name: "Validate Gradle Wrapper"
on:
    push:
        branches:
            - master
            - 'v*-branch'
    pull_request:

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          use-policy-store: true
          egress-policy: audit
          api-key: ${{ secrets.STEP_SECURITY_API_KEY }}

      - uses: actions/checkout@v6
      - uses: Wandalen/wretry.action@v3.8.0
        name: Gradle Validation
        continue-on-error: true
        with:
          action: gradle/wrapper-validation-action@v1
          attempt_limit: 3
          attempt_delay: 2000
