name: Create issues from To-Dos

on:
    workflow_dispatch:
        inputs:
            importAll:
                default: "false"
                required: false
                type: boolean
                description: Enable, if you want to import all TODOs. Runs on checked out branch! Only use if you're sure what you are doing.
#   push: Will move this to a cadence
#     branches:
#       - master

permissions:
    issues: write
    repository-projects: read
    contents: read

jobs:
    todos:
        name: Scan for To-Dos
        runs-on: ubuntu-latest

        steps:
            - name: Harden the runner
              uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
              with:
                use-policy-store: true
                egress-policy: audit
                api-key: ${{ secrets.STEP_SECURITY_API_KEY }}

            - name: Checkout
              uses: actions/checkout@v6
            - name: Run Issue Bot
              uses: derjuulsn/todo-issue@main
              with:
                  #           autoAssign: false
                  reopenClosed: false
                  #           label: "todo"
                  # disabled until this works: https://github.com/DerJuulsn/todo-issue/issues/9
                  keywords: "todo,fixme,bug,TODO,FIXME,BUG"
                  excludePattern: "^(node_modules/|third_party/|zzz_generated/|docs/|.vscode/)"
              env:
                  GITHUB_TOKEN: ${{ secrets.MATTER_PAT }}
